### ISSUE TITLE
Mentees should be able to see their active requests

### ISSUE THREAD

**Issue by tsg** [tupuio/tupuapp#13]
### Feature Description

Similar to how the Mentors have a "Requests" page that shows the mentorship requests they received, the Mentees should have a "My requests" page where they should see their active (and perhaps also old, in a separate tab) requests and their status.

**Tasks**
- [x] #17
- [x] #19
- [x] Create page `ApplicationsPage` 
    - [x] for listing the applications including `ApplicationsList`, similarly to [RequestsPage](https://github.com/tupuio/tupuapp/blob/a361b9b38aa379b98971f7c89b26f21b96d9a343/pages/requests.js#L4)
    - [x] with Text: 
        ```
        You have sent the application for mentorship to the following people. Please, be patient, they will accept or deny your application. You can cancel an application at anytime, please provide a kind message to the mentor while doing so.
        ```
- [x] Add `Applications` menu entry
  - [x] with the same icon of `Requests`, see [SidebarContent.js L25-L26](https://github.com/tupuio/tupuapp/blob/439e5ea873eda282a45e7b995a565cb068f076ee/components/Sidebar/SidebarContent.js#L25-L26)
  - [x] the route (`href`) should be `/applications`
  - [x] the tag should be `applicationsCount` set to `0` as for now.
  - [x] Update the `SidebarContent`, with fetching the `applicationsCount` from the endpoint `/api/applicationsCount`

### Screenshots

![image](https://user-images.githubusercontent.com/6698585/153075815-ef3df6b8-ed6f-45c2-8d2a-37b7f898d562.png)

---

<img width="960" alt="image" src="https://user-images.githubusercontent.com/6698585/153505397-dc8c0387-2ab8-406b-912a-6106d86492d7.png">
